name: gpu-carbon-estimator-demo
description: estimates carbon emissions from gpu power usage
tags:
initialize:
  plugins:
    gpu-carbon-estimator:
      method: GpuCarbonEstimator
      path: gpu-carbon-estimator
tree:
  children:
    child:
      pipeline:
        - gpu-carbon-estimator
      defaults:
        region: "GB"
      inputs:
        - timestamp: '2024-01-01T00:00:00Z'
          duration: 60  # seconds
          gpu/power-usage: 50  # watts
        - timestamp: '2024-01-01T00:01:00Z'
          duration: 60  # seconds
          gpu/power-usage: 80  # watts
